
@startuml render

!include public.wsd

namespace render {
    interface RenderLibrary {
        RenderTargetTextuteBuilder createRenderTarget()
    }
    RenderLibrary::createRenderTarget ..> target.RenderTargetTextuteBuilder : <<return>>
}

@enduml
