name: Build

on:
    workflow_dispatch:
    push:
        branches: 
            - '*'
    pull_request:
        branches:
            - '*'

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3

    - name: Maven Verify
      run: mvn -B clean verify -f MoonEngine

    - name: Test Coverage
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

